name: qafeel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  # Core
  connectivity_plus: ^6.1.2
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.4
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3

  #Bloc
  flutter_bloc: ^9.1.1

  #Shared Preference
  shared_preferences: ^2.5.1

  #Freezed
  # freezed_annotation: ^2.4.4

  #Firebase
  # firebase_core: ^3.10.1
  # cloud_firestore: ^5.6.11

  #Image Picker
  image_picker: ^1.1.2
  permission_handler: ^11.3.1

  #API
  # dio: ^5.8.0+1
  # pretty_dio_logger: ^1.4.0
  # retrofit: ^4.4.2
  # json_annotation: ^4.9.0
  # flutter:
  #   sdk: flutter

dev_dependencies:

  flutter_lints: ^5.0.0
  very_good_analysis: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  # dart run build_runner build --delete-conflicting-outputs
  # build_runner: ^2.4.14
  # freezed: ^2.4.6
  # retrofit_generator: ^9.1.7
  # json_serializable: ^6.7.1
  # hive_generator: ^2.0.1

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - lang/ar.json
    - lang/en.json
    - .env.dev
    - .env.prod
    - assets/images/
    - assets/icons/
  # example:
  fonts:
    # Arabic Fonts
    - family: Arabic-Avenir
      fonts:
        - asset: assets/fonts/arabic/avenir_arabic/AvenirArabic-Heavy.otf
          weight: 900
        - asset: assets/fonts/arabic/avenir_arabic/AvenirArabic-Medium.otf
          weight: 800
        - asset: assets/fonts/arabic/avenir_arabic/AvenirArabic-Light.otf
          weight: 500
    # English Fonts
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 800
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 500
